### ISSUE TITLE
Move the UI from apps-rewards-android

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish-client-android#15]
### Reason

Implement the client UI

### Description

Move the UI slice from apps-rewards-android and start refactoring and adapting the moved files

### Success Criteria

- [ ] example app is able to initialize the UI

**Comment by Schuler-Gabriel** [comment]
- move all packages to an UI folder inside client project
-  analyze all dependencies needed, adding only the fundamentals one to the client project
- start creating an account slice for account adding the ui and the account class, removing the status property and changing the accountProvider to EmailProviderEnum
-  add the offers and largestContributors functions on Rewards capture slice to CloService class deleting the rest
-  move the Card, CardNetwork and CardRepository classes to clo package and move the functions in CardService to CloService
- move the AuthKeys and Ui to the slice, add the drawable.gmail image to the client project and add the function resId in EmailEnum to EmailProviderEnum
- move all Classes (changing properties on LicenseKeys gmailClientId and outlookClientId insted of microblinck ones) to license slice
-  more and navigation stays the same
-  delete retailer package and delete it from the navigation.
- add components and theme packages from utils to the ui slice
- the remaining flies stays inside the ui package
- adapt all functions on Rewards  and keep in ui, delete or move the others functions
- move all tests and adapt it
