### ISSUE TITLE
Cleanup and review the UIs

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish-client-android#18]
### Reason

verify that the UIs match the UX for demo

### Description

Cleanup the UIs to make sure it all works and match the specs.

### Success Criteria

- [ ] UIs match specs
- [ ] Navigation and account login/logout is mocked

**Comment by Schuler-Gabriel** [comment]
- review each screen to see if matches the new figma design
- mock account screen to wok without needing api, because it might not be done at the moment
