### ISSUE TITLE
Initialization refactor

### ISSUE THREAD

**Issue by Schuler-Gabriel** [tiki/publish-client-android#55]
### Reason
We need to change the initialization process of the sdk

### Description

To facilitate the initialization of the sdk for the user a build pattern was choosed.
the initialization must be made in a way that the user using the followind code will be able to access all functionalities of the sdk such as license and capture:

```kotlin
val config = Config(
            providerId = "PROVIDER_ID",
            publicKey = "PUBLIC_KEY",
            companyName = "COMPANY_NAME",
            companyJurisdiction = "US",
            tosUrl = "TERMS_URL",
            privacyUrl = "PRIVACY_URL"
        )
        TikiClient.configure(config)
        TikiClient.initialize("USER_ID")
```

### Success Criteria

- [x] TikiClient being initialized correctly

**Comment by ricardobrg** [comment]
done in #61
